In [2]:
import numpy as np
import torch

In [257]:
x = torch.tensor([[3, 4, 1], [2, 4, 2]])
y = torch.tensor([1, 2])
x_score = torch.tensor([[3, 1, 4], [2, 4, 3]])
y_pred = torch.tensor([2, 1])
delta = 0

In [347]:
x_score = torch.tensor([[3, 1, 4], [2, 4, 3]])

In [348]:
x_score

tensor([[3, 1, 4],
        [2, 4, 3]])

In [349]:
y

tensor([1, 2])

In [352]:
x_score[[0, 1], y]

tensor([1, 3])

In [353]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [354]:
num_sample = x_score.shape[0]
yi_score = x_score[torch.arange(num_sample), y]

In [355]:
yi_score

tensor([1, 3])

In [357]:
margins = x_score - yi_score.reshape(-1, 1) + delta
# margins[torch.arange(num_sample), y] = 0
margins = torch.max(torch.zeros_like(margins), margins)
loss = torch.sum(margins)

In [213]:
torch.mean(torch.sum(margins, 1))

RuntimeError: Can only calculate the mean of floating types. Got Long instead.

In [358]:
margins

tensor([[2, 0, 3],
        [0, 1, 0]])

In [361]:
index = margins

In [362]:
index[margins > 0] = 1

In [363]:
index

tensor([[1, 0, 1],
        [0, 1, 0]])

In [248]:
index[np.arange(num_sample), y] = -1

In [249]:
index

tensor([[ 1, -1,  1],
        [ 0,  1, -1]])

In [261]:
binary = np.array([[1, 0, 1],
        [0, 1, 0]])

In [367]:
row_sum = torch.sum(index, 1)

In [368]:
row_sum

tensor([2, 1])

In [370]:
index[torch.arange(2), y] = -row_sum

In [371]:
index

tensor([[ 1, -2,  1],
        [ 0,  1, -1]])

In [263]:
row_sum = np.sum(binary, axis=1)

In [264]:
row_sum

array([2, 1])

In [269]:
from collections import namedtuple
Result = namedtuple('Result', 'accuracy loss')

In [271]:
t = Result(accuracy=[], loss=[])

In [278]:
t.accuracy.append(0.6)

In [279]:
t

Result(accuracy=[0.4, 0.6], loss=[])

In [337]:
a = torch.arange(6).reshape(2,3)
b = torch.arange(6, 15).reshape(3,3)

In [338]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [339]:
b

tensor([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [342]:
a * a

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [341]:
torch.sum(a * a, 1)

tensor([ 5, 50])

In [340]:
torch.sum(a * a, 1).reshape(-1, 1)

tensor([[ 5],
        [50]])

In [343]:
b * b

tensor([[ 36,  49,  64],
        [ 81, 100, 121],
        [144, 169, 196]])

In [344]:
torch.sum(b * b, 1)

tensor([149, 302, 509])

In [326]:
b * b

tensor([[ 36,  49,  64],
        [ 81, 100, 121],
        [144, 169, 196]])

In [345]:
torch.mm(a, torch.t(b))

tensor([[ 23,  32,  41],
        [ 86, 122, 158]])

In [331]:
torch.sum(a * a, 1).reshape(-1, 1) - 2 * torch.mm(a, torch.t(b))

tensor([[ -41,  -59,  -77],
        [-122, -194, -266]])

In [346]:
torch.sum(a * a, 1).reshape(-1, 1) - 2 * torch.mm(a, torch.t(b)) + torch.sum(b * b, 1)

tensor([[108, 243, 432],
        [ 27, 108, 243]])

In [333]:
torch.mm(a, torch.t(b))

tensor([[ 23,  32,  41],
        [ 86, 122, 158]])

In [334]:
2 * torch.mm(a, torch.t(b))

tensor([[ 46,  64,  82],
        [172, 244, 316]])

In [336]:
torch.mode(torch.tensor([1, 2, 1, 1]))

(tensor(1), tensor(3))

In [4]:
np.array([5, 6])

array([5, 6])